use crate::models::Position;

#[derive(Debug, Clone)]
pub struct ParsedPlayer {
    pub shirt_number: i32,
    pub position: Position,
    pub first_name: &'static str,
    pub last_name: &'static str,
    pub goals_per_match: &'static [(usize, u32)],
    pub active: bool,
}

#[derive(Debug, Clone)]
pub struct ParsedTeam {
    pub name: &'static str,
}

#[derive(Debug, Clone)]
pub struct ParsedMatch {
    pub col_index: usize,
    pub opponent: &'static str,
    pub is_home: bool,
    pub home_score: i32,
    pub away_score: i32,
    pub date_time: &'static str,
}

pub static PLAYERS: &[ParsedPlayer] = &[
    ParsedPlayer {
        shirt_number: 1,
        first_name: "Boris",
        last_name: "Bertens",
        position: Position::DefensiveMidfielder,
        goals_per_match: &[
            (18usize, 1u32),
            (38usize, 1u32),
            (39usize, 9u32),
            (41usize, 1u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 2,
        first_name: "Gijs",
        last_name: "Bertens",
        position: Position::Striker,
        goals_per_match: &[(41usize, 2u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 3,
        first_name: "Danny",
        last_name: "Borremans",
        position: Position::LeftWinger,
        goals_per_match: &[
            (7usize, 1u32),
            (38usize, 1u32),
            (39usize, 9u32),
            (41usize, 3u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 4,
        first_name: "Stef",
        last_name: "Bosmans",
        position: Position::AttackingMidfielder,
        goals_per_match: &[
            (6usize, 2u32),
            (38usize, 2u32),
            (39usize, 6u32),
            (41usize, 4u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 5,
        first_name: "Thiebe",
        last_name: "Breugelmans",
        position: Position::CentreBack,
        goals_per_match: &[
            (6usize, 1u32),
            (7usize, 1u32),
            (22usize, 1u32),
            (38usize, 3u32),
            (39usize, 4u32),
            (41usize, 5u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 6,
        first_name: "Bart",
        last_name: "Cammaert",
        position: Position::LeftWinger,
        goals_per_match: &[
            (7usize, 1u32),
            (18usize, 1u32),
            (38usize, 2u32),
            (39usize, 6u32),
            (41usize, 6u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 7,
        first_name: "Jelle",
        last_name: "Cammaert",
        position: Position::RightWinger,
        goals_per_match: &[
            (2usize, 1u32),
            (4usize, 1u32),
            (9usize, 1u32),
            (10usize, 1u32),
            (15usize, 1u32),
            (21usize, 1u32),
            (38usize, 6u32),
            (39usize, 3u32),
            (41usize, 7u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 8,
        first_name: "Ronny",
        last_name: "Canters",
        position: Position::DefensiveMidfielder,
        goals_per_match: &[
            (18usize, 1u32),
            (25usize, 1u32),
            (38usize, 2u32),
            (39usize, 6u32),
            (41usize, 8u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 9,
        first_name: "Pascal",
        last_name: "Cuylits",
        position: Position::Striker,
        goals_per_match: &[(41usize, 9u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 10,
        first_name: "Bert",
        last_name: "De Backer",
        position: Position::RightBack,
        goals_per_match: &[(41usize, 10u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 11,
        first_name: "Bram",
        last_name: "De Backer",
        position: Position::Striker,
        goals_per_match: &[
            (4usize, 2u32),
            (5usize, 2u32),
            (8usize, 3u32),
            (9usize, 2u32),
            (13usize, 1u32),
            (16usize, 1u32),
            (18usize, 1u32),
            (19usize, 1u32),
            (26usize, 1u32),
            (38usize, 14u32),
            (39usize, 1u32),
            (41usize, 11u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 12,
        first_name: "Kjell",
        last_name: "Denissen",
        position: Position::LeftBack,
        goals_per_match: &[(41usize, 12u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 13,
        first_name: "Joey",
        last_name: "De Waal",
        position: Position::LeftBack,
        goals_per_match: &[(41usize, 13u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 14,
        first_name: "Quinten",
        last_name: "Jacobs",
        position: Position::CentreBack,
        goals_per_match: &[(41usize, 14u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 15,
        first_name: "Jeroen",
        last_name: "Renders",
        position: Position::Goalkeeper,
        goals_per_match: &[(41usize, 15u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 16,
        first_name: "Thomas",
        last_name: "Robeyns",
        position: Position::RightWinger,
        goals_per_match: &[
            (5usize, 4u32),
            (7usize, 1u32),
            (9usize, 2u32),
            (19usize, 1u32),
            (38usize, 8u32),
            (39usize, 2u32),
            (41usize, 16u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 17,
        first_name: "Itse",
        last_name: "Van Nijlen",
        position: Position::RightBack,
        goals_per_match: &[
            (18usize, 1u32),
            (19usize, 1u32),
            (20usize, 1u32),
            (38usize, 3u32),
            (39usize, 4u32),
            (41usize, 17u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 18,
        first_name: "Kristof",
        last_name: "Willemse",
        position: Position::CentreBack,
        goals_per_match: &[
            (14usize, 1u32),
            (38usize, 1u32),
            (39usize, 9u32),
            (41usize, 18u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 19,
        first_name: "Jani",
        last_name: "Breugelmans",
        position: Position::RightWinger,
        goals_per_match: &[
            (3usize, 1u32),
            (38usize, 1u32),
            (39usize, 9u32),
            (41usize, 19u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 20,
        first_name: "Gastspeler(s)",
        last_name: "",
        position: Position::CentralMidfielder,
        goals_per_match: &[
            (6usize, 1u32),
            (8usize, 1u32),
            (9usize, 1u32),
            (10usize, 1u32),
            (11usize, 1u32),
            (13usize, 1u32),
            (14usize, 2u32),
            (17usize, 2u32),
            (19usize, 2u32),
            (25usize, 7u32),
            (27usize, 3u32),
            (38usize, 22u32),
            (41usize, 20u32),
        ],
        active: false,
    },
    ParsedPlayer {
        shirt_number: 22,
        first_name: "Werner",
        last_name: "Swaegers",
        position: Position::CentreBack,
        goals_per_match: &[(41usize, 22u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 23,
        first_name: "Jan",
        last_name: "Jacobs",
        position: Position::Goalkeeper,
        goals_per_match: &[(41usize, 23u32)],
        active: true,
    },
];

pub static TEAMS: &[ParsedTeam] = &[
    ParsedTeam {
        name: "Duivenmelkers",
    },
    ParsedTeam { name: "White Star" },
    ParsedTeam {
        name: "Fanfare Merksplas",
    },
    ParsedTeam { name: "Dokters" },
    ParsedTeam { name: "De Nok" },
    ParsedTeam {
        name: "Oud-Turnhout",
    },
    ParsedTeam {
        name: "Vet Oosthoven",
    },
    ParsedTeam {
        name: "Dynamo Beirs",
    },
    ParsedTeam {
        name: "Fanfare Merlsplas",
    },
    ParsedTeam { name: "Harlem 22" },
    ParsedTeam { name: "Unitas" },
    ParsedTeam {
        name: "Witte Brecht",
    },
    ParsedTeam {
        name: "Schoonbroek",
    },
    ParsedTeam {
        name: "Heidelopers",
    },
    ParsedTeam { name: "Zandhoven" },
];

pub static MATCHES: &[ParsedMatch] = &[
    ParsedMatch {
        col_index: 2usize,
        opponent: "Duivenmelkers",
        is_home: true,
        home_score: 1,
        away_score: 0,
        date_time: "2025-01-04T14:30:00+01:00",
    },
    ParsedMatch {
        col_index: 3usize,
        opponent: "White Star",
        is_home: true,
        home_score: 1,
        away_score: 0,
        date_time: "2025-01-18T13:30:00+01:00",
    },
    ParsedMatch {
        col_index: 4usize,
        opponent: "Fanfare Merksplas",
        is_home: false,
        home_score: 2,
        away_score: 3,
        date_time: "2025-02-07T19:30:00+01:00",
    },
    ParsedMatch {
        col_index: 5usize,
        opponent: "Dokters",
        is_home: true,
        home_score: 6,
        away_score: 2,
        date_time: "2025-02-15T15:00:00+01:00",
    },
    ParsedMatch {
        col_index: 6usize,
        opponent: "De Nok",
        is_home: false,
        home_score: 1,
        away_score: 4,
        date_time: "2025-02-21T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 7usize,
        opponent: "Oud-Turnhout",
        is_home: true,
        home_score: 4,
        away_score: 1,
        date_time: "2025-03-01T13:30:00+01:00",
    },
    ParsedMatch {
        col_index: 8usize,
        opponent: "Vet Oosthoven",
        is_home: false,
        home_score: 2,
        away_score: 4,
        date_time: "2025-03-14T19:30:00+01:00",
    },
    ParsedMatch {
        col_index: 9usize,
        opponent: "Dynamo Beirs",
        is_home: true,
        home_score: 6,
        away_score: 2,
        date_time: "2025-03-22T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 10usize,
        opponent: "Oud-Turnhout",
        is_home: false,
        home_score: 5,
        away_score: 2,
        date_time: "2025-03-29T15:00:00+01:00",
    },
    ParsedMatch {
        col_index: 11usize,
        opponent: "Fanfare Merlsplas",
        is_home: true,
        home_score: 1,
        away_score: 3,
        date_time: "2025-04-12T13:30:00+02:00",
    },
    ParsedMatch {
        col_index: 12usize,
        opponent: "White Star",
        is_home: false,
        home_score: 2,
        away_score: 0,
        date_time: "2025-04-18T19:00:00+02:00",
    },
    ParsedMatch {
        col_index: 13usize,
        opponent: "Harlem 22",
        is_home: false,
        home_score: 0,
        away_score: 2,
        date_time: "2025-01-01T19:00:00+02:00",
    },
    ParsedMatch {
        col_index: 14usize,
        opponent: "Unitas",
        is_home: false,
        home_score: 2,
        away_score: 3,
        date_time: "2025-04-25T20:00:00+02:00",
    },
    ParsedMatch {
        col_index: 15usize,
        opponent: "Unitas",
        is_home: true,
        home_score: 1,
        away_score: 0,
        date_time: "2025-01-01T19:00:00+02:00",
    },
    ParsedMatch {
        col_index: 16usize,
        opponent: "Witte Brecht",
        is_home: true,
        home_score: 1,
        away_score: 3,
        date_time: "2025-08-09T15:00:00+02:00",
    },
    ParsedMatch {
        col_index: 17usize,
        opponent: "Schoonbroek",
        is_home: false,
        home_score: 1,
        away_score: 2,
        date_time: "2025-01-01T19:00:00+02:00",
    },
    ParsedMatch {
        col_index: 18usize,
        opponent: "Heidelopers",
        is_home: false,
        home_score: 0,
        away_score: 5,
        date_time: "2025-01-01T19:00:00+02:00",
    },
    ParsedMatch {
        col_index: 19usize,
        opponent: "Duivenmelkers",
        is_home: true,
        home_score: 5,
        away_score: 1,
        date_time: "2025-09-13T14:30:00+02:00",
    },
    ParsedMatch {
        col_index: 20usize,
        opponent: "Oud-Turnhout",
        is_home: true,
        home_score: 1,
        away_score: 1,
        date_time: "2025-09-20T13:30:00+02:00",
    },
    ParsedMatch {
        col_index: 21usize,
        opponent: "Unitas",
        is_home: false,
        home_score: 3,
        away_score: 1,
        date_time: "2025-10-04T15:00:00+02:00",
    },
    ParsedMatch {
        col_index: 22usize,
        opponent: "Fanfare Merksplas",
        is_home: false,
        home_score: 1,
        away_score: 1,
        date_time: "2025-12-12T19:30:00+01:00",
    },
    ParsedMatch {
        col_index: 23usize,
        opponent: "White star",
        is_home: false,
        home_score: 3,
        away_score: 0,
        date_time: "2025-10-25T13:30:00+02:00",
    },
    ParsedMatch {
        col_index: 24usize,
        opponent: "Vet Oosthoven",
        is_home: false,
        home_score: 1,
        away_score: 0,
        date_time: "2025-10-31T19:30:00+01:00",
    },
    ParsedMatch {
        col_index: 25usize,
        opponent: "Dokters",
        is_home: true,
        home_score: 9,
        away_score: 3,
        date_time: "2025-11-08T15:00:00+01:00",
    },
    ParsedMatch {
        col_index: 26usize,
        opponent: "Zandhoven",
        is_home: true,
        home_score: 1,
        away_score: 4,
        date_time: "2025-12-05T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 27usize,
        opponent: "White Star",
        is_home: true,
        home_score: 3,
        away_score: 0,
        date_time: "2025-12-20T13:30:00+01:00",
    },
];
