use crate::models::Position;

#[derive(Debug, Clone)]
pub struct ParsedPlayer {
    pub shirt_number: i32,
    pub position: Position,
    pub first_name: &'static str,
    pub last_name: &'static str,
    pub goals_per_match: &'static [(usize, u32)],
    pub active: bool,
}

#[derive(Debug, Clone)]
pub struct ParsedTeam {
    pub name: &'static str,
}

#[derive(Debug, Clone)]
pub struct ParsedMatch {
    pub col_index: usize,
    pub opponent: &'static str,
    pub is_home: bool,
    pub home_score: i32,
    pub away_score: i32,
    pub date_time: &'static str,
}

pub static PLAYERS: &[ParsedPlayer] = &[
    ParsedPlayer {
        shirt_number: 1,
        first_name: "Boris",
        last_name: "Bertens",
        position: Position::DefensiveMidfielder,
        goals_per_match: &[(18usize, 1u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 2,
        first_name: "Gijs",
        last_name: "Bertens",
        position: Position::Striker,
        goals_per_match: &[],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 3,
        first_name: "Danny",
        last_name: "Borremans",
        position: Position::LeftWinger,
        goals_per_match: &[(7usize, 1u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 4,
        first_name: "Stef",
        last_name: "Bosmans",
        position: Position::AttackingMidfielder,
        goals_per_match: &[(6usize, 2u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 5,
        first_name: "Thiebe",
        last_name: "Breugelmans",
        position: Position::CentreBack,
        goals_per_match: &[(6usize, 1u32), (7usize, 1u32), (22usize, 1u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 6,
        first_name: "Bart",
        last_name: "Cammaert",
        position: Position::LeftWinger,
        goals_per_match: &[(7usize, 1u32), (18usize, 1u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 7,
        first_name: "Jelle",
        last_name: "Cammaert",
        position: Position::RightWinger,
        goals_per_match: &[
            (2usize, 1u32),
            (4usize, 1u32),
            (9usize, 1u32),
            (10usize, 1u32),
            (15usize, 1u32),
            (21usize, 1u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 8,
        first_name: "Ronny",
        last_name: "Canters",
        position: Position::DefensiveMidfielder,
        goals_per_match: &[(18usize, 1u32), (25usize, 1u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 9,
        first_name: "Pascal",
        last_name: "Cuylits",
        position: Position::Striker,
        goals_per_match: &[],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 10,
        first_name: "Bert",
        last_name: "De Backer",
        position: Position::RightBack,
        goals_per_match: &[],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 11,
        first_name: "Bram",
        last_name: "De Backer",
        position: Position::Striker,
        goals_per_match: &[
            (4usize, 2u32),
            (5usize, 2u32),
            (8usize, 3u32),
            (9usize, 2u32),
            (13usize, 1u32),
            (16usize, 1u32),
            (18usize, 1u32),
            (19usize, 1u32),
            (26usize, 1u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 12,
        first_name: "Kjell",
        last_name: "Denissen",
        position: Position::LeftBack,
        goals_per_match: &[],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 13,
        first_name: "Joey",
        last_name: "De Waal",
        position: Position::LeftBack,
        goals_per_match: &[],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 14,
        first_name: "Quinten",
        last_name: "Jacobs",
        position: Position::CentreBack,
        goals_per_match: &[],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 15,
        first_name: "Jeroen",
        last_name: "Renders",
        position: Position::Goalkeeper,
        goals_per_match: &[],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 16,
        first_name: "Thomas",
        last_name: "Robeyns",
        position: Position::RightWinger,
        goals_per_match: &[
            (5usize, 4u32),
            (7usize, 1u32),
            (9usize, 2u32),
            (19usize, 1u32),
        ],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 17,
        first_name: "Itse",
        last_name: "Van Nijlen",
        position: Position::RightBack,
        goals_per_match: &[(18usize, 1u32), (19usize, 1u32), (20usize, 1u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 18,
        first_name: "Kristof",
        last_name: "Willemse",
        position: Position::CentreBack,
        goals_per_match: &[(14usize, 1u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 19,
        first_name: "Jani",
        last_name: "Breugelmans",
        position: Position::RightWinger,
        goals_per_match: &[(3usize, 1u32)],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 20,
        first_name: "Gastspeler(s)",
        last_name: "",
        position: Position::CentralMidfielder,
        goals_per_match: &[
            (6usize, 1u32),
            (8usize, 1u32),
            (9usize, 1u32),
            (10usize, 1u32),
            (11usize, 1u32),
            (13usize, 1u32),
            (14usize, 2u32),
            (17usize, 2u32),
            (19usize, 2u32),
            (25usize, 7u32),
            (27usize, 3u32),
        ],
        active: false,
    },
    ParsedPlayer {
        shirt_number: 22,
        first_name: "Werner",
        last_name: "Swaegers",
        position: Position::CentreBack,
        goals_per_match: &[],
        active: true,
    },
    ParsedPlayer {
        shirt_number: 23,
        first_name: "Jan",
        last_name: "Jacobs",
        position: Position::Goalkeeper,
        goals_per_match: &[],
        active: true,
    },
];

pub static TEAMS: &[ParsedTeam] = &[
    ParsedTeam {
        name: "Duivenmelkers",
    },
    ParsedTeam { name: "White Star" },
    ParsedTeam {
        name: "Fanfare Merksplas",
    },
    ParsedTeam { name: "Dokters" },
    ParsedTeam { name: "De Nok" },
    ParsedTeam {
        name: "Oud-Turnhout",
    },
    ParsedTeam {
        name: "Vet Oosthoven",
    },
    ParsedTeam {
        name: "Dynamo Beirs",
    },
    ParsedTeam {
        name: "Fanfare Merlsplas",
    },
    ParsedTeam { name: "Harlem 22" },
    ParsedTeam { name: "Unitas" },
    ParsedTeam {
        name: "Witte Brecht",
    },
    ParsedTeam {
        name: "Schoonbroek",
    },
    ParsedTeam {
        name: "Heidelopers",
    },
    ParsedTeam { name: "Zandhoven" },
    ParsedTeam { name: "Mengelmoes" },
    ParsedTeam { name: "Gelmelboys" },
    ParsedTeam {
        name: "FC Broekkant",
    },
    ParsedTeam { name: "Weelde" },
];

pub static MATCHES: &[ParsedMatch] = &[
    // === 2025 season (completed) ===
    ParsedMatch {
        col_index: 2,
        opponent: "Duivenmelkers",
        is_home: true,
        home_score: 1,
        away_score: 0,
        date_time: "2025-01-04T14:30:00+01:00",
    },
    ParsedMatch {
        col_index: 3,
        opponent: "White Star",
        is_home: true,
        home_score: 1,
        away_score: 0,
        date_time: "2025-01-18T13:30:00+01:00",
    },
    ParsedMatch {
        col_index: 4,
        opponent: "Fanfare Merksplas",
        is_home: false,
        home_score: 2,
        away_score: 3,
        date_time: "2025-02-07T19:30:00+01:00",
    },
    ParsedMatch {
        col_index: 5,
        opponent: "Dokters",
        is_home: true,
        home_score: 6,
        away_score: 2,
        date_time: "2025-02-15T15:00:00+01:00",
    },
    ParsedMatch {
        col_index: 6,
        opponent: "De Nok",
        is_home: false,
        home_score: 1,
        away_score: 4,
        date_time: "2025-02-21T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 7,
        opponent: "Oud-Turnhout",
        is_home: true,
        home_score: 4,
        away_score: 1,
        date_time: "2025-03-01T13:30:00+01:00",
    },
    ParsedMatch {
        col_index: 8,
        opponent: "Vet Oosthoven",
        is_home: false,
        home_score: 2,
        away_score: 4,
        date_time: "2025-03-14T19:30:00+01:00",
    },
    ParsedMatch {
        col_index: 9,
        opponent: "Dynamo Beirs",
        is_home: true,
        home_score: 6,
        away_score: 2,
        date_time: "2025-03-22T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 10,
        opponent: "Oud-Turnhout",
        is_home: false,
        home_score: 5,
        away_score: 2,
        date_time: "2025-03-29T15:00:00+01:00",
    },
    ParsedMatch {
        col_index: 11,
        opponent: "Fanfare Merlsplas",
        is_home: true,
        home_score: 1,
        away_score: 3,
        date_time: "2025-04-12T13:30:00+02:00",
    },
    ParsedMatch {
        col_index: 12,
        opponent: "White Star",
        is_home: false,
        home_score: 2,
        away_score: 0,
        date_time: "2025-04-18T19:00:00+02:00",
    },
    ParsedMatch {
        col_index: 13,
        opponent: "Harlem 22",
        is_home: false,
        home_score: 0,
        away_score: 2,
        date_time: "2025-01-01T19:00:00+02:00",
    },
    ParsedMatch {
        col_index: 14,
        opponent: "Unitas",
        is_home: false,
        home_score: 2,
        away_score: 3,
        date_time: "2025-04-25T20:00:00+02:00",
    },
    ParsedMatch {
        col_index: 15,
        opponent: "Unitas",
        is_home: true,
        home_score: 1,
        away_score: 0,
        date_time: "2025-01-01T19:00:00+02:00",
    },
    ParsedMatch {
        col_index: 16,
        opponent: "Witte Brecht",
        is_home: true,
        home_score: 1,
        away_score: 3,
        date_time: "2025-08-09T15:00:00+02:00",
    },
    ParsedMatch {
        col_index: 17,
        opponent: "Schoonbroek",
        is_home: false,
        home_score: 1,
        away_score: 2,
        date_time: "2025-01-01T19:00:00+02:00",
    },
    ParsedMatch {
        col_index: 18,
        opponent: "Heidelopers",
        is_home: false,
        home_score: 0,
        away_score: 5,
        date_time: "2025-01-01T19:00:00+02:00",
    },
    ParsedMatch {
        col_index: 19,
        opponent: "Duivenmelkers",
        is_home: true,
        home_score: 5,
        away_score: 1,
        date_time: "2025-09-13T14:30:00+02:00",
    },
    ParsedMatch {
        col_index: 20,
        opponent: "Oud-Turnhout",
        is_home: true,
        home_score: 1,
        away_score: 1,
        date_time: "2025-09-20T13:30:00+02:00",
    },
    ParsedMatch {
        col_index: 21,
        opponent: "Unitas",
        is_home: false,
        home_score: 3,
        away_score: 1,
        date_time: "2025-10-04T15:00:00+02:00",
    },
    ParsedMatch {
        col_index: 22,
        opponent: "Fanfare Merksplas",
        is_home: false,
        home_score: 1,
        away_score: 1,
        date_time: "2025-12-12T19:30:00+01:00",
    },
    ParsedMatch {
        col_index: 23,
        opponent: "White Star",
        is_home: false,
        home_score: 3,
        away_score: 0,
        date_time: "2025-10-25T13:30:00+02:00",
    },
    ParsedMatch {
        col_index: 24,
        opponent: "Vet Oosthoven",
        is_home: false,
        home_score: 1,
        away_score: 0,
        date_time: "2025-10-31T19:30:00+01:00",
    },
    ParsedMatch {
        col_index: 25,
        opponent: "Dokters",
        is_home: true,
        home_score: 9,
        away_score: 3,
        date_time: "2025-11-08T15:00:00+01:00",
    },
    ParsedMatch {
        col_index: 26,
        opponent: "Zandhoven",
        is_home: true,
        home_score: 1,
        away_score: 4,
        date_time: "2025-12-05T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 27,
        opponent: "White Star",
        is_home: true,
        home_score: 3,
        away_score: 0,
        date_time: "2025-12-20T13:30:00+01:00",
    },
    // === 2026 season (scheduled) ===
    ParsedMatch {
        col_index: 30,
        opponent: "Duivenmelkers",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-01-10T14:30:00+01:00",
    },
    ParsedMatch {
        col_index: 31,
        opponent: "Zandhoven",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-01-16T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 32,
        opponent: "Mengelmoes",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-01-24T13:30:00+01:00",
    },
    ParsedMatch {
        col_index: 33,
        opponent: "White Star",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-01-31T13:30:00+01:00",
    },
    ParsedMatch {
        col_index: 34,
        opponent: "Dokters",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-02-07T15:00:00+01:00",
    },
    ParsedMatch {
        col_index: 35,
        opponent: "Fanfare Merksplas",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-02-13T19:30:00+01:00",
    },
    ParsedMatch {
        col_index: 36,
        opponent: "Heidelopers",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-02-21T15:00:00+01:00",
    },
    ParsedMatch {
        col_index: 37,
        opponent: "De Nok",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-02-27T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 38,
        opponent: "Unitas",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-03-06T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 39,
        opponent: "Oud-Turnhout",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-03-14T13:30:00+01:00",
    },
    ParsedMatch {
        col_index: 40,
        opponent: "Unitas",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-03-20T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 41,
        opponent: "Gelmelboys",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-04-11T15:00:00+02:00",
    },
    ParsedMatch {
        col_index: 42,
        opponent: "Zandhoven",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-04-17T20:00:00+02:00",
    },
    ParsedMatch {
        col_index: 43,
        opponent: "Fanfare Merksplas",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-04-24T19:30:00+02:00",
    },
    ParsedMatch {
        col_index: 44,
        opponent: "FC Broekkant",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-05-02T14:00:00+02:00",
    },
    ParsedMatch {
        col_index: 45,
        opponent: "Weelde",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-08-01T14:00:00+02:00",
    },
    ParsedMatch {
        col_index: 46,
        opponent: "Witte Brecht",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-08-08T15:00:00+02:00",
    },
    ParsedMatch {
        col_index: 47,
        opponent: "Dokters",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-09-19T15:00:00+02:00",
    },
    ParsedMatch {
        col_index: 48,
        opponent: "Fanfare Merksplas",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-09-25T19:30:00+02:00",
    },
    ParsedMatch {
        col_index: 49,
        opponent: "Oud-Turnhout",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-10-03T13:30:00+02:00",
    },
    ParsedMatch {
        col_index: 50,
        opponent: "Duivenmelkers",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-10-10T14:30:00+02:00",
    },
    ParsedMatch {
        col_index: 51,
        opponent: "Zandhoven",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-10-16T20:00:00+02:00",
    },
    ParsedMatch {
        col_index: 52,
        opponent: "Unitas",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-10-23T20:00:00+02:00",
    },
    ParsedMatch {
        col_index: 53,
        opponent: "Oud-Turnhout",
        is_home: false,
        home_score: 0,
        away_score: 0,
        date_time: "2026-11-14T13:30:00+01:00",
    },
    ParsedMatch {
        col_index: 54,
        opponent: "Fanfare Merksplas",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-11-20T19:30:00+01:00",
    },
    ParsedMatch {
        col_index: 55,
        opponent: "Unitas",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-12-04T20:00:00+01:00",
    },
    ParsedMatch {
        col_index: 56,
        opponent: "Dokters",
        is_home: true,
        home_score: 0,
        away_score: 0,
        date_time: "2026-12-12T15:00:00+01:00",
    },
];
